name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {java-version: '17', distribution: 'temurin'}
      - uses: android-actions/setup-android@v3
      - uses: gradle/gradle-build-action@v2
        with: {gradle-version: '8.5', cache-disabled: true}
      - name: Build
        run: |
          find . -name "app" -type d | head -n 1 | xargs dirname | xargs cd
          echo "android.useAndroidX=true" > gradle.properties
          gradle assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with: {name: 'TheBeat-App', path: '**/*.apk'}
